---
# Do prerequesite before kubenetes install 

- name: disable swap
  command: swapoff -a

- name: ensure swap disable at boot
  replace:
    path: /etc/fstab
    regexp: '^(.+?\sswap\s+sw\s+.*)$'
    replace: '# \1'

#  shell: sed -i '/swap/d' /etc/fstab

- name: Disable Firewall
  service: 
    name: firewalld
    state: stopped
    enabled: no

- name:	Setup selinux on master and nodes
  lineinfile:
   path: /etc/selinux/config
   state: present
   regexp: '^%SELINUX='
   line: '^%SELINUX=permissive'

#  shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config 

- name: update Iptables
  copy: 
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: reload sysctl 
  command: sysctl --system

- name: configure kubernets repo 
  copy: 
    src: kubernets.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install Kubenetes
  yum: 
    name: [ 'kubelet', 'kubeadm', 'kubectl' ]
    state: installed 


- name: enable kubelet 
  systemd:
    name: kubelet
    enabled: yes
