---
- name: Install Prerequesite
  yum: 
    name: yum-utils
    state: installed
    
- name: Add docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  yum: 
    name: docker-ce-18.06.2.ce
    state: present 

- name: Create Docker directory 
  file: 
    path: /etc/docker 
    state: directory 

- name: copy deamon file
  copy: 
    src: daemon.json
    dest: /etc/docker/daemon.json 

- name: create systemd docker directory 
  command: mkdir -p /etc/systemd/system/docker.service.d

- name: start docker
  systemd: 
    state: restarted
    name: docker
    daemon_reload: yes